// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/v1/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{0}
}

func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (m *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(m, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMessage) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserMessage) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	UserMessage          *UserMessage `protobuf:"bytes,1,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUserMessage() *UserMessage {
	if m != nil {
		return m.UserMessage
	}
	return nil
}

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{3}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type ListUsersResponse struct {
	UserMessages         []*UserMessage `protobuf:"bytes,1,rep,name=user_messages,json=userMessages,proto3" json:"user_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{4}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUserMessages() []*UserMessage {
	if m != nil {
		return m.UserMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*UserMessage)(nil), "v1.user.UserMessage")
	proto.RegisterType((*GetUserRequest)(nil), "v1.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "v1.user.GetUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "v1.user.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "v1.user.ListUsersResponse")
}

func init() { proto.RegisterFile("protos/v1/user/user.proto", fileDescriptor_c15b69877c1b4d97) }

var fileDescriptor_c15b69877c1b4d97 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x4d, 0x05, 0x21, 0x4c, 0x51, 0x71, 0x63, 0xc2, 0xc2, 0x09, 0x7b, 0xc2, 0x03, 0xdd, 0x80,
	0x07, 0x63, 0xe2, 0x89, 0x8b, 0xd1, 0x28, 0x87, 0x26, 0x5e, 0xbc, 0x10, 0x90, 0x49, 0x29, 0xc9,
	0x76, 0xb1, 0xd3, 0xe5, 0x1b, 0xfc, 0x6c, 0xb3, 0x43, 0x53, 0x8b, 0xca, 0xa5, 0x99, 0xf7, 0xde,
	0xcc, 0xbc, 0x37, 0xe9, 0x42, 0x6f, 0x9b, 0x99, 0xdc, 0x90, 0xda, 0x8d, 0x95, 0x25, 0xcc, 0xf8,
	0x13, 0x32, 0x27, 0x9a, 0xbb, 0x71, 0xe8, 0x60, 0x60, 0xc0, 0x7f, 0x23, 0xcc, 0x5e, 0x91, 0x68,
	0x11, 0xa3, 0xe8, 0x42, 0xd3, 0xd1, 0xf3, 0x64, 0x25, 0xbd, 0x81, 0x37, 0x6c, 0x45, 0x0d, 0x07,
	0x9f, 0x56, 0x42, 0x40, 0x3d, 0x5d, 0x68, 0x94, 0x27, 0xcc, 0x72, 0x2d, 0xae, 0xa1, 0xbd, 0x5d,
	0x9b, 0x14, 0xe7, 0xa9, 0xd5, 0x4b, 0xcc, 0x64, 0x8d, 0x35, 0x9f, 0xb9, 0x19, 0x53, 0xa2, 0x03,
	0xb5, 0x45, 0x8c, 0xb2, 0x3e, 0xf0, 0x86, 0xa7, 0x91, 0x2b, 0x83, 0x1b, 0x38, 0x7f, 0xc4, 0xdc,
	0x79, 0x46, 0xf8, 0x69, 0x91, 0xf2, 0xa3, 0x9e, 0xc1, 0x33, 0x5c, 0x94, 0xad, 0xb4, 0x35, 0x29,
	0xa1, 0xb8, 0x83, 0x36, 0xf7, 0xea, 0x7d, 0x5e, 0x1e, 0xf0, 0x27, 0x57, 0x61, 0x71, 0x4e, 0x58,
	0xb9, 0x25, 0xf2, 0xed, 0x0f, 0x08, 0x04, 0x74, 0x5e, 0x12, 0xe2, 0x65, 0x54, 0x18, 0x07, 0x33,
	0xb8, 0xac, 0x70, 0x85, 0xc3, 0x3d, 0x9c, 0x55, 0x1d, 0x48, 0x7a, 0x83, 0xda, 0x51, 0x8b, 0x76,
	0xc5, 0x82, 0x26, 0x5f, 0x1e, 0xd4, 0x9d, 0x2a, 0x1e, 0xa0, 0x59, 0x04, 0x17, 0xdd, 0x72, 0xee,
	0xf0, 0xea, 0xbe, 0xfc, 0x2b, 0x14, 0x09, 0xa6, 0xd0, 0x2a, 0x63, 0x89, 0x5e, 0xd9, 0xf6, 0x3b,
	0x7e, 0xbf, 0xff, 0x9f, 0xb4, 0xdf, 0x31, 0x1d, 0xbf, 0xab, 0x38, 0xc9, 0xd7, 0x76, 0x19, 0x7e,
	0x18, 0xad, 0xf4, 0x86, 0x36, 0x49, 0x4a, 0x56, 0xf1, 0xcf, 0x1f, 0xc5, 0x66, 0x44, 0x56, 0xab,
	0xc3, 0xd7, 0xb1, 0x6c, 0x30, 0xbe, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x59, 0x05, 0xb0, 0x9e,
	0x36, 0x02, 0x00, 0x00,
}
